### ISSUE TITLE
Webpack integration for isomor-transpiler?

### ISSUE THREAD

**Issue by x7airworker** [apiel/isomor#16]
As the title says I want to know if the isomor-transpiler can be used with webpack, which would make many things easier.

**Comment by apiel** [comment]
Can you give more details about what you have in mind?

**Comment by x7airworker** [comment]
Initially I wanted to write a library like this myself. And because there would be a few problems with using a default Vue project, I had a look at NuxtJS (in the React world this would be NextJS, which is somewhat equivalent). I could add the isomor-server into a serverMiddleware of the express based SSR renderer, but at the same time I would also like to have some deeper integrated build cycle, so I thought this would be easy if I could just add isomor-transpiler to the webpack configuration

**Comment by apiel** [comment]
The problem is that I am not so familiar with Webpack and most of the time, I try to avoid to play with it :p So far isomor is generating an API client library in the background to call the function on the server. I guess to use it with NuxtJs, you would have to somehow hook the isomor server into the Nuxt server, have a look at https://github.com/apiel/isomor/tree/master/packages/isomor-server , you could import `isomor-server` and instantiate it inside Nuxt. Then for the rest, I don't even think you need to do anything special, just run the transpiler in watch mode and it should generate the api client as module, you can import inside your Vue application.

I didn't touch this project for a while, as I was a bit annoyed about all this concept of client side application, too much overwhelming to make a simple web application that in most case don't need such complex frontend (so lately I was going back to the oldschool style doing JSX on the server with https://github.com/apiel/jsx-html and using vanillaJS for the little interaction I needed in browser). Finally React world come up with new concept, called React Server Components https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html , that is actually solving most of the issues I had with frontend programming. So I don't think I will put more energy into isomor, anyhow I am still happy if I can support you ;-)

**Comment by x7airworker** [comment]
Okay thank you.
